# see https://release-plz.ieni.dev/docs/github for more information

name: Release

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: "Token to publish to crates.io"
        required: true

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
